In [31]:
%matplotlib inline

In [32]:
from sklearn import datasets
import numpy as np
import matplotlib.pyplot as plt

In [33]:
boston = datasets.load_boston()
X, y = boston.data, boston.target
print "X shape is: ", X.shape
print X

X shape is:  (506, 13)
[[  6.32000000e-03   1.80000000e+01   2.31000000e+00 ...,   1.53000000e+01
    3.96900000e+02   4.98000000e+00]
 [  2.73100000e-02   0.00000000e+00   7.07000000e+00 ...,   1.78000000e+01
    3.96900000e+02   9.14000000e+00]
 [  2.72900000e-02   0.00000000e+00   7.07000000e+00 ...,   1.78000000e+01
    3.92830000e+02   4.03000000e+00]
 ..., 
 [  6.07600000e-02   0.00000000e+00   1.19300000e+01 ...,   2.10000000e+01
    3.96900000e+02   5.64000000e+00]
 [  1.09590000e-01   0.00000000e+00   1.19300000e+01 ...,   2.10000000e+01
    3.93450000e+02   6.48000000e+00]
 [  4.74100000e-02   0.00000000e+00   1.19300000e+01 ...,   2.10000000e+01
    3.96900000e+02   7.88000000e+00]]


In [34]:
print "y shape is: ", y.shape
print y

y shape is:  (506,)
[ 24.   21.6  34.7  33.4  36.2  28.7  22.9  27.1  16.5  18.9  15.   18.9
  21.7  20.4  18.2  19.9  23.1  17.5  20.2  18.2  13.6  19.6  15.2  14.5
  15.6  13.9  16.6  14.8  18.4  21.   12.7  14.5  13.2  13.1  13.5  18.9
  20.   21.   24.7  30.8  34.9  26.6  25.3  24.7  21.2  19.3  20.   16.6
  14.4  19.4  19.7  20.5  25.   23.4  18.9  35.4  24.7  31.6  23.3  19.6
  18.7  16.   22.2  25.   33.   23.5  19.4  22.   17.4  20.9  24.2  21.7
  22.8  23.4  24.1  21.4  20.   20.8  21.2  20.3  28.   23.9  24.8  22.9
  23.9  26.6  22.5  22.2  23.6  28.7  22.6  22.   22.9  25.   20.6  28.4
  21.4  38.7  43.8  33.2  27.5  26.5  18.6  19.3  20.1  19.5  19.5  20.4
  19.8  19.4  21.7  22.8  18.8  18.7  18.5  18.3  21.2  19.2  20.4  19.3
  22.   20.3  20.5  17.3  18.8  21.4  15.7  16.2  18.   14.3  19.2  19.6
  23.   18.4  15.6  18.1  17.4  17.1  13.3  17.8  14.   14.4  13.4  15.6
  11.8  13.8  15.6  14.6  17.8  15.4  21.5  19.6  15.3  19.4  17.   15.6
  13.1  41.3  24.3  23.3  27.  

In [35]:
print "Mean = ", X[:, :3].mean(axis=0)
print "Std  = ", X[:, :3].std(axis=0)

Mean =  [  3.59376071  11.36363636  11.13677866]
Std  =  [  8.58828355  23.29939569   6.85357058]


# 数据预处理：

### z-score标准化：
标准分数（standard score）也叫z分数（z-score）,是一个分数与平均数的差再除以标准差的过程。
用公式表示为：

$$z=\frac{x-\mu}{\sigma}$$

其中$x$为某一具体分数，$\mu$为平均数，$\sigma$为标准差。
$Z$值的量代表着原始分数和母体平均值之间的距离，是以标准差为单位计算。在原始分数低于平均值时$Z$则为负数，反之则为正数。

In [52]:
from sklearn import preprocessing

print X[:, :3]
#Standardize features by removing the mean and scaling to unit variance
X_2 = preprocessing.scale(X[:, :3])
print X_2
print "Scaled Mean = ", X_2.mean(axis=0)
print "Scaled Std  = ", X_2.std(axis=0)

[[  6.32000000e-03   1.80000000e+01   2.31000000e+00]
 [  2.73100000e-02   0.00000000e+00   7.07000000e+00]
 [  2.72900000e-02   0.00000000e+00   7.07000000e+00]
 ..., 
 [  6.07600000e-02   0.00000000e+00   1.19300000e+01]
 [  1.09590000e-01   0.00000000e+00   1.19300000e+01]
 [  4.74100000e-02   0.00000000e+00   1.19300000e+01]]
[[-0.41771335  0.28482986 -1.2879095 ]
 [-0.41526932 -0.48772236 -0.59338101]
 [-0.41527165 -0.48772236 -0.59338101]
 ..., 
 [-0.41137448 -0.48772236  0.11573841]
 [-0.40568883 -0.48772236  0.11573841]
 [-0.41292893 -0.48772236  0.11573841]]
Scaled Mean =  [  6.34099712e-17  -6.34319123e-16  -2.68291099e-15]
Scaled Std  =  [ 1.  1.  1.]


### 线性函数转换

$$X\_std = \frac{X - X.min(axis=0)}{X.max(axis=0) - X.min(axis=0)}$$

$$X\_scaled = \frac{X\_std}{max - min} + min$$

说明：$X\_scaled$为转换后的值，$X.max, X.min$分别为样本的最大值和最小值，$max, min$分别为转换范围的最大值和最小值。

In [48]:
my_minmax_scaler = preprocessing.MinMaxScaler() # 默认转换范围为(0, 1)
my_minmax_scaler.fit(X[:, :3])
#my_minmax_scaler.transform(X[:, :3]).mean(axis=0)
my_minmax_scaler.transform(X[:, :3])

array([[  0.00000000e+00,   1.80000000e-01,   6.78152493e-02],
       [  2.35922539e-04,   0.00000000e+00,   2.42302053e-01],
       [  2.35697744e-04,   0.00000000e+00,   2.42302053e-01],
       ..., 
       [  6.11892474e-04,   0.00000000e+00,   4.20454545e-01],
       [  1.16072990e-03,   0.00000000e+00,   4.20454545e-01],
       [  4.61841693e-04,   0.00000000e+00,   4.20454545e-01]])

### Normalization

**Normalization** is the process of **scaling individual samples to have unit norm (length of 1)**. This process can be useful if you plan to use a quadratic form such as the dot-product or any other kernel to quantify the similarity of any pair of samples.
This assumption is the base of the ***Vector Space Model*** often used in text classification and clustering contexts.

In [54]:
normalized_X = preprocessing.normalize(X[:, :3]) # use either L1 or L2 norms, default is L2 norms.
normalized_X

array([[  3.48255018e-04,   9.91865557e-01,   1.27289413e-01],
       [  3.86277175e-03,   0.00000000e+00,   9.99992539e-01],
       [  3.85994296e-03,   0.00000000e+00,   9.99992550e-01],
       ..., 
       [  5.09297670e-03,   0.00000000e+00,   9.99987031e-01],
       [  9.18569794e-03,   0.00000000e+00,   9.99957811e-01],
       [  3.97398371e-03,   0.00000000e+00,   9.99992104e-01]])

### creating binary features through thresholding

In [59]:
Y = boston.target.reshape(1, -1)
new_target = preprocessing.binarize(Y, threshold=Y.mean())
new_target[0, :5]

array([ 1.,  0.,  1.,  1.,  1.])

### working with categorical variables

In [72]:
iris = datasets.load_iris()
X = iris.data
y = iris.target
d = np.column_stack((X, y))
text_encoder = preprocessing.OneHotEncoder()
text_encoder.fit_transform(d[:, -1:]).toarray()[:5]

array([[ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.]])