In [6]:
from sklearn import datasets
from sklearn import preprocessing
import numpy as np

In [16]:
boston = datasets.load_boston()
X, y = boston.data, boston.target
print X

[[  6.32000000e-03   1.80000000e+01   2.31000000e+00 ...,   1.53000000e+01
    3.96900000e+02   4.98000000e+00]
 [  2.73100000e-02   0.00000000e+00   7.07000000e+00 ...,   1.78000000e+01
    3.96900000e+02   9.14000000e+00]
 [  2.72900000e-02   0.00000000e+00   7.07000000e+00 ...,   1.78000000e+01
    3.92830000e+02   4.03000000e+00]
 ..., 
 [  6.07600000e-02   0.00000000e+00   1.19300000e+01 ...,   2.10000000e+01
    3.96900000e+02   5.64000000e+00]
 [  1.09590000e-01   0.00000000e+00   1.19300000e+01 ...,   2.10000000e+01
    3.93450000e+02   6.48000000e+00]
 [  4.74100000e-02   0.00000000e+00   1.19300000e+01 ...,   2.10000000e+01
    3.96900000e+02   7.88000000e+00]]


In [11]:
X[:, :3].mean(axis=0)

array([  3.59376071,  11.36363636,  11.13677866])

In [12]:
X[:, :3].std(axis=0)

array([  8.58828355,  23.29939569,   6.85357058])

In [14]:
X_2 = preprocessing.scale(X[:, :3])
X_2[:, :3].mean(axis=0)

array([  6.34099712e-17,  -6.34319123e-16,  -2.68291099e-15])

In [15]:
X_2[:, :3].std(axis=0)

array([ 1.,  1.,  1.])